"use client";
import { useEffect, useState } from "react";

export default function ProductsPage() {
  const [products, setProducts] = useState<any[]>([]); const [show, setShow] = useState(false); const [error, setError] = useState(""); const [form, setForm] = useState({ name: "", sku: "", kind: "PRODUCT", unit: "יחידה", costPrice: "", salePrice: "", reorderPoint: "", reorderQuantity: "", description: "" });
  const load = () => fetch("/api/inventory/products").then(async r => { const d = await r.json(); if (!r.ok) throw new Error(d.error); return d; }).then(d => setProducts(d.products || [])).catch(e => setError(e.message));
  useEffect(() => { load(); }, []);
  const save = async (e: React.FormEvent) => { e.preventDefault(); const r = await fetch("/api/inventory/products", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const d = await r.json(); if (!r.ok) { setError(d.error); return; } setShow(false); setForm({ name: "", sku: "", kind: "PRODUCT", unit: "יחידה", costPrice: "", salePrice: "", reorderPoint: "", reorderQuantity: "", description: "" }); load(); };
  return <div className="space-y-5"><div className="flex justify-between items-center"><div><h1 className="text-2xl font-bold">קטלוג מוצרים ושירותים</h1><p className="text-sm" style={{ color: "var(--muted)" }}>מוצרים, סננים, חלקים, שירותים וחבילות</p></div><button onClick={() => setShow(!show)} className="btn-accent">מוצר/שירות חדש</button></div>{error && <div className="p-3 rounded" style={{ background: "#ffebee", color: "#c62828" }}>{error}</div>}{show && <form onSubmit={save} className="card p-5 grid grid-cols-2 gap-3"><Field label="שם" value={form.name} set={(v: string) => setForm({ ...form, name: v })} required /><Field label="מק״ט" value={form.sku} set={(v: string) => setForm({ ...form, sku: v })} required /><label className="text-sm">סוג<select className="input-field" value={form.kind} onChange={e => setForm({ ...form, kind: e.target.value })}><option value="PRODUCT">מוצר פיזי</option><option value="SERVICE">שירות</option><option value="BUNDLE">חבילה</option></select></label><Field label="יחידת מידה" value={form.unit} set={(v: string) => setForm({ ...form, unit: v })} /><Field label="מחיר עלות" value={form.costPrice} set={(v: string) => setForm({ ...form, costPrice: v })} type="number" /><Field label="מחיר מכירה" value={form.salePrice} set={(v: string) => setForm({ ...form, salePrice: v })} type="number" /><Field label="נקודת הזמנה" value={form.reorderPoint} set={(v: string) => setForm({ ...form, reorderPoint: v })} type="number" /><Field label="כמות להזמנה" value={form.reorderQuantity} set={(v: string) => setForm({ ...form, reorderQuantity: v })} type="number" /><label className="text-sm col-span-2">תיאור<textarea className="input-field" value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} /></label><button className="btn-accent">שמור</button></form>}<div className="card overflow-hidden"><table className="w-full text-sm"><thead><tr className="border-b"><th className="p-3 text-right">שם</th><th className="p-3 text-right">מק״ט</th><th className="p-3 text-right">סוג</th><th className="p-3 text-right">מחיר עלות</th><th className="p-3 text-right">מחיר מכירה</th><th className="p-3 text-right">מלאי</th></tr></thead><tbody>{products.map(p => <tr key={p.id} className="border-b"><td className="p-3 font-medium">{p.name}</td><td className="p-3 font-mono">{p.sku}</td><td className="p-3">{p.kind === "SERVICE" ? "שירות" : p.kind === "BUNDLE" ? "חבילה" : "מוצר"}</td><td className="p-3">₪{p.costPrice.toLocaleString()}</td><td className="p-3">₪{p.salePrice.toLocaleString()}</td><td className="p-3">{p.inventoryItems?.reduce((sum: number, i: any) => sum + i.quantityOnHand - i.quantityReserved, 0) || 0}</td></tr>)}</tbody></table>{!products.length && <p className="p-8 text-center" style={{ color: "var(--muted)" }}>אין מוצרים עדיין.</p>}</div></div>;
}
function Field({ label, value, set, type = "text", required = false }: any) { return <label className="text-sm">{label}<input className="input-field" type={type} value={value} onChange={e => set(e.target.value)} required={required} /></label>; }



