"use client";
import { useEffect, useState } from "react";
import Link from "next/link";

export default function OrdersPage() {
  const [orders, setOrders] = useState<any[]>([]);
  const [appointments, setAppointments] = useState<any[]>([]);
  const [showNew, setShowNew] = useState(false);
  const [message, setMessage] = useState("");
  const load = async () => { const [o, a] = await Promise.all([fetch("/api/orders").then(r => r.json()), fetch("/api/order-calendar").then(r => r.json())]); setOrders(o.orders || []); setAppointments(a.appointments || []); };
  useEffect(() => { load(); }, []);
  const move = async (id: string, startAt: string) => { const r = await fetch(`/api/orders/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ scheduledAt: startAt }) }); setMessage(r.ok ? "מועד ההזמנה עודכן והיומן סונכרן" : "לא ניתן לעדכן מועד"); load(); };
  return <div className="space-y-5"><div className="flex justify-between items-center"><div><h1 className="text-2xl font-bold">הזמנות</h1><p className="text-sm" style={{ color: "var(--muted)" }}>רשימת הזמנות, תזמון ויומן שירות והתקנות</p></div><button className="btn-accent" onClick={() => setShowNew(!showNew)}>הזמנה חדשה</button></div>{message && <div className="p-3 rounded" style={{ background: "#e8f5e9", color: "#2e7d32" }}>{message}</div>}{showNew && <NewOrder onSaved={() => { setShowNew(false); load(); }} />}
    <div className="grid grid-cols-1 xl:grid-cols-2 gap-4"><section className="card overflow-hidden"><div className="p-4 font-bold">רשימת הזמנות</div><table className="w-full text-sm"><thead><tr className="border-b" style={{ borderColor: "var(--border)" }}><th className="text-right p-3">מספר</th><th className="text-right p-3">לקוח</th><th className="text-right p-3">סטטוס</th><th className="text-right p-3">סכום</th><th className="text-right p-3">מועד</th></tr></thead><tbody>{orders.map(o => <tr key={o.id} className="border-b" style={{ borderColor: "var(--border)" }}><td className="p-3 font-mono">{o.orderNumber}</td><td className="p-3"><Link href={`/customers/${o.customerId}`} style={{ color: "var(--rust)" }}>{o.customer.name}</Link></td><td className="p-3">{o.status}</td><td className="p-3 font-mono">₪{o.total.toLocaleString()}</td><td className="p-3">{o.scheduledAt ? new Date(o.scheduledAt).toLocaleString("he-IL") : "לא נקבע"}</td></tr>)}</tbody></table>{!orders.length && <div className="p-8 text-center" style={{ color: "var(--muted)" }}>אין הזמנות</div>}</section>
      <section className="card p-4"><div className="font-bold mb-3">יומן הזמנות — גרירה לשינוי מועד</div><p className="text-xs mb-3" style={{ color: "var(--muted)" }}>גרור כרטיס הזמנה ליום/שעה אחרת. השינוי נשמר גם בהזמנה וגם ביומן.</p><div className="grid grid-cols-5 gap-2">{Array.from({ length: 5 }).map((_, i) => { const d = new Date(); d.setDate(d.getDate() + i); const key = d.toISOString().slice(0, 10); return <div key={key} className="border rounded min-h-48 p-2" style={{ borderColor: "var(--border)" }} onDragOver={e => e.preventDefault()} onDrop={e => { const id = e.dataTransfer.getData("orderId"); if (id) move(id, `${key}T09:00:00`); }}><div className="text-xs font-bold mb-2">{d.toLocaleDateString("he-IL", { weekday: "short", day: "numeric" })}</div>{appointments.filter(a => a.startAtUtc.slice(0, 10) === key).map(a => <div key={a.id} draggable onDragStart={e => e.dataTransfer.setData("orderId", a.orderId)} className="p-2 rounded mb-2 text-xs cursor-grab" style={{ background: "#e8f0fe" }}><strong>{a.order?.orderNumber}</strong><br />{a.customer.name}<br />{new Date(a.startAtUtc).toLocaleTimeString("he-IL", { hour: "2-digit", minute: "2-digit" })}</div>)}</div>; })}</div></section></div></div>;
}
function NewOrder({ onSaved }: { onSaved: () => void }) { const [customers, setCustomers] = useState<any[]>([]); const [f, setF] = useState({ customerId: "", title: "", type: "SERVICE", total: "", scheduledAt: "", notes: "" }); const [error, setError] = useState(""); useEffect(() => { fetch("/api/customers").then(r => r.json()).then(d => setCustomers(d.customers || [])); }, []); const submit = async (e: React.FormEvent) => { e.preventDefault(); const r = await fetch("/api/orders", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...f, total: Number(f.total || 0) }) }); const d = await r.json(); if (!r.ok) { setError(d.error || "שגיאה"); return; } onSaved(); }; return <section className="card p-5"><h2 className="font-bold mb-3">יצירת הזמנה חדשה</h2>{error && <p style={{ color: "#c62828" }}>{error}</p>}<form onSubmit={submit} className="grid grid-cols-2 gap-3"><select className="input-field" value={f.customerId} onChange={e => setF({ ...f, customerId: e.target.value })} required><option value="">בחר לקוח</option>{customers.map(c => <option key={c.id} value={c.id}>{c.name} · {c.phone}</option>)}</select><input className="input-field" placeholder="כותרת הזמנה" value={f.title} onChange={e => setF({ ...f, title: e.target.value })} required /><select className="input-field" value={f.type} onChange={e => setF({ ...f, type: e.target.value })}><option value="SERVICE">שירות</option><option value="INSTALLATION">התקנה</option><option value="FILTER_REPLACEMENT">החלפת סננים</option></select><input className="input-field" type="number" placeholder="סכום" value={f.total} onChange={e => setF({ ...f, total: e.target.value })} /><input className="input-field" type="datetime-local" value={f.scheduledAt} onChange={e => setF({ ...f, scheduledAt: e.target.value })} /><textarea className="input-field" placeholder="הערות" value={f.notes} onChange={e => setF({ ...f, notes: e.target.value })} /><button className="btn-accent col-span-2">שמור הזמנה ויומן</button></form></section>; }

