"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";

export default function NewLeadPage() {
  const router = useRouter();
  const [f, setF] = useState({ name: "", phone: "", email: "", company: "", city: "", source: "WEBSITE", stage: "NEW", confidence: "MEDIUM", interests: "", currentSystem: "", value: "", notes: "", utm_source: "", utm_campaign: "", utm_adset: "" });
  const [error, setError] = useState(""); const set = (k: string, v: string) => setF({ ...f, [k]: v });
  const submit = async (e: React.FormEvent) => { e.preventDefault(); const r = await fetch("/api/leads", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...f, value: f.value ? Number(f.value) : null, interests: f.interests.split(",").map(x => x.trim()).filter(Boolean), utmData: { utm_source: f.utm_source, utm_campaign: f.utm_campaign, utm_adset: f.utm_adset } }) }); const d = await r.json(); if (!r.ok) { setError(d.error || "לא ניתן ליצור ליד"); return; } router.push(`/leads/${d.lead.id}`); };
  return <div className="max-w-4xl mx-auto space-y-4"><h1 className="text-3xl font-bold">קליטת ליד ידנית</h1>{error && <div className="p-3 rounded" style={{ background: "#ffebee", color: "#c62828" }}>{error}</div>}<form onSubmit={submit} className="card p-5 grid grid-cols-2 gap-4"><Field l="שם פרטי ומשפחה *" v={f.name} set={v => set("name", v)} /><Field l="טלפון ראשי *" v={f.phone} set={v => set("phone", v)} /><Field l="אימייל" v={f.email} set={v => set("email", v)} /><Field l="חברה" v={f.company} set={v => set("company", v)} /><Field l="עיר / אזור" v={f.city} set={v => set("city", v)} /><Field l="תחום עניין (פסיקים)" v={f.interests} set={v => set("interests", v)} /><Field l="מצב נוכחי" v={f.currentSystem} set={v => set("currentSystem", v)} /><Field l="הצעת מחיר" v={f.value} set={v => set("value", v)} /><Select l="מקור" v={f.source} set={v => set("source", v)} opts={[["WEBSITE", "אתר"], ["FACEBOOK", "Facebook"], ["INSTAGRAM", "Instagram"], ["REFERRAL", "המלצה"], ["WHATSAPP", "WhatsApp"], ["GMAIL", "Gmail"], ["OTHER", "אחר"]]} /><Select l="סטטוס" v={f.stage} set={v => set("stage", v)} opts={[["NEW", "חדש"], ["CONTACTED", "בשיחה"], ["QUALIFIED", "מוכשר"], ["PROPOSAL", "נשלחה הצעה"], ["WON", "סגר והזמין"], ["LOST", "לא רלוונטי"]]} /><Field l="utm_source" v={f.utm_source} set={v => set("utm_source", v)} /><Field l="utm_campaign" v={f.utm_campaign} set={v => set("utm_campaign", v)} /><Field l="utm_adset" v={f.utm_adset} set={v => set("utm_adset", v)} /><label className="col-span-2 text-sm">הערות<textarea className="input-field" rows={4} value={f.notes} onChange={e => set("notes", e.target.value)} /></label><button className="btn-accent col-span-2">צור ליד ופתח כרטיס</button></form></div>;
}
function Field({ l, v, set }: { l: string; v: string; set: (v: string) => void }) { return <label className="text-sm">{l}<input className="input-field" value={v} onChange={e => set(e.target.value)} required={l.includes("*")} /></label>; }
function Select({ l, v, set, opts }: { l: string; v: string; set: (v: string) => void; opts: string[][] }) { return <label className="text-sm">{l}<select className="input-field" value={v} onChange={e => set(e.target.value)}>{opts.map(([x, y]) => <option key={x} value={x}>{y}</option>)}</select></label>; }

