import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { can } from "@/lib/permissions";
import { TechnicianProfileStatus } from "@prisma/client";
export const dynamic = "force-dynamic";
async function guard(action = "view") { const s = await getServerSession(authOptions); if (!s) return { error: NextResponse.json({ error: "לא מחובר" }, { status: 401 }) }; if (!can((s.user as any).role, "fieldTech", action)) return { error: NextResponse.json({ error: "אין הרשאה" }, { status: 403 }) }; return { session: s }; }
export async function GET(_req: NextRequest, { params }: { params: Promise<{ id: string }> }) { const g = await guard(); if (g.error) return g.error; const { id } = await params; const t = await prisma.technicianProfile.findUnique({ where: { id }, include: { user: { select: { id: true, name: true, email: true, phone: true, isActive: true } }, skills: true, serviceAreas: true, availability: true, locations: { orderBy: { recordedAt: "desc" }, take: 20 }, assignments: { include: { serviceCall: { include: { customer: true } } }, orderBy: { assignedAt: "desc" }, take: 100 }, inventory: { include: { product: true } }, statusHistory: { orderBy: { createdAt: "desc" }, take: 30 } } }); if (!t) return NextResponse.json({ error: "טכנאי לא נמצא" }, { status: 404 }); return NextResponse.json({ technician: t }); }
export async function PATCH(req: NextRequest, { params }: { params: Promise<{ id: string }> }) { const g = await guard("edit"); if (g.error) return g.error; const { id } = await params; const b = await req.json(); const before = await prisma.technicianProfile.findUnique({ where: { id } }); if (!before) return NextResponse.json({ error: "טכנאי לא נמצא" }, { status: 404 }); const status = b.status as TechnicianProfileStatus | undefined; const updated = await prisma.$transaction(async tx => { const p = await tx.technicianProfile.update({ where: { id }, data: { ...(b.name !== undefined ? { user: { update: { name: b.name } } } : {}), ...(b.phone !== undefined ? { phone: b.phone || null, user: { update: { phone: b.phone || null } } } : {}), ...(b.employeeNumber !== undefined ? { employeeNumber: b.employeeNumber || null } : {}), ...(status && Object.values(TechnicianProfileStatus).includes(status) ? { status } : {}), ...(b.baseAddress !== undefined ? { baseAddress: b.baseAddress || null } : {}), ...(b.baseCity !== undefined ? { baseCity: b.baseCity || null } : {}), ...(b.baseRegion !== undefined ? { baseRegion: b.baseRegion || null } : {}), ...(b.baseLat !== undefined ? { baseLat: b.baseLat === null ? null : Number(b.baseLat) } : {}), ...(b.baseLng !== undefined ? { baseLng: b.baseLng === null ? null : Number(b.baseLng) } : {}), ...(b.serviceRadiusKm !== undefined ? { serviceRadiusKm: b.serviceRadiusKm === null ? null : Number(b.serviceRadiusKm) } : {}), ...(b.teamName !== undefined ? { teamName: b.teamName || null } : {}), ...(b.notes !== undefined ? { notes: b.notes || null } : {}), ...(b.maxCallsPerDay !== undefined ? { maxCallsPerDay: b.maxCallsPerDay ? Number(b.maxCallsPerDay) : null } : {}), ...(b.emergencyAvailable !== undefined ? { emergencyAvailable: Boolean(b.emergencyAvailable) } : {}) } }); if (status && status !== before.status) await tx.technicianStatusLog.create({ data: { technicianId: id, oldStatus: before.status, newStatus: status, changedById: (g.session!.user as any).id, reason: b.reason || null } }); return p; }); return NextResponse.json({ technician: updated }); }


